sudo: false
notifications:
  irc:
    channels: "chat.freenode.net#firedrake"
    skip_join: true
    on_success: change
    on_failure: always
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} | %{build_url}"
language: python
python:
  - "3.4"

before_install:
  - pip install --upgrade pip
  - pip install flake8
  - pip install pytest

install:
  - pip install .

script:
  - flake8 .
  - DATA_REPO_GIT="" py.test test/
