image: ubuntu:16.04

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install python-minimal python-pip python-pytest python-setuptools python-wheel --no-install-recommends
          - apt-get install python3-minimal python3-pip python3-pytest python3-setuptools python3-wheel --no-install-recommends
          - pip install .
          - pip3 install .
          - cd test/
          - DATA_REPO_GIT="" py.test .
          - DATA_REPO_GIT="" py.test-3 .
