image: python:2.7

pipelines:
  default:
    - step:
        script:
          - pip install -e .
          - pip install pytest
          - pip install nose
          - cd test/
          - py.test .