image: ubuntu:16.04

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y
              git
              python-minimal python-pip python-pytest python-setuptools python-wheel
              python3-minimal python3-pip python3-pytest python3-setuptools python3-wheel
              --no-install-recommends
          - pip2 install flake8 flake8-future-import
          - pip3 install flake8 flake8-future-import
          - pip2 install .
          - pip3 install .
          - python2 -m flake8
          - python3 -m flake8
          - DATA_REPO_GIT="" python2 -m pytest -v test/
          - DATA_REPO_GIT="" python3 -m pytest -v test/
