version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory:  ~/fiat-test
    steps:
      - checkout
      - run:
          name: Install dependencies  # Install with sudo as tests not run as superuser in circleci/python
          command: sudo pip install flake8 pytest pytest-cases numpy sympy coverage coveralls --upgrade
      - run:
          name: Install FIAT
          command: pip install . --user
      - run:
          name: Run flake8 tests
          command: python -m flake8 .
      - run:
          name: Run unit tests
          command: |
	      DATA_REPO_GIT="" coverage run --source FIAT -m pytest -v test/
              coveralls